### ISSUE TITLE
What does your development environment look like?

### ISSUE THREAD

**Issue by arthurvr** [najela/ama#3]
Editor, terminal, ...

**Comment by najela** [comment]
I use a 15" MacBook Pro with OS X 10.10

Editor: Atom with [atom-material-ui](https://atom.io/themes/atom-material-ui)  and [atom-material-syntax](https://github.com/silvestreh/atom-material-syntax). I use emacs occasionally

I also use [Chromium](https://www.chromium.org/) and Tor(https://www.torproject.org/)

Terminal: Iterm2 with oh-my-zh

If you need more specs, I'll be happy to provide

**Comment by venkatramanareddy** [comment]
Yes! we would like to know more!

**Comment by najela** [comment]
@venkatramanareddy What would you like to know exactly?
