### ISSUE TITLE
What do you like to eat?

### ISSUE THREAD

**Issue by arthurvr** [najela/ama#4]

**Comment by najela** [comment]
I'll kick off with this. *well I :heart:  food*

I like mostly traditional Meals. 

Eru 
![10299786_286715111505366_2047121194_n](https://igcdn-photos-g-a.akamaihd.net/hphotos-ak-xat1/t51.2885-15/10299786_286715111505366_2047121194_n.jpg)

Ndole
![Ndole](https://igcdn-photos-f-a.akamaihd.net/hphotos-ak-xaf1/t51.2885-15/11385240_1616080052008629_1980772929_n.jpg)

Biftek
![Biftek}
![2015-06-08 10 43 27](https://cloud.githubusercontent.com/assets/4196457/8896385/0219f00a-33f2-11e5-8ce7-ad4e7ba5eea8.jpg)
